apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogeyJhdXRoIjogImRtRjZaMlZ1TTJzNloybDBhSFZpWDNCaGRGOHhNVUpCV2tSTVQxRXdkWFpRY1RSMWVrNXRNRE5JWHpoalFVTnpTa2xRY3psVFFrcFZUbFo0VkdoU1pXa3dPRTFJZVRNNFJWSjVhVXRXZUdVNFZERXljRVpJTkVWT05WWkdXVnB5WXpSR1JsWXkifSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0K==
type: kubernetes.io/dockerconfigjson
